baseURL: "http://localhost:1313/"
title: Not A Shopping Note
paginate: 9
theme: coyote

menu:
  main:
    - identifier: search
      name: Search
      url: search/
outputs:
    home:
        - HTML
        - JSON
